#ifndef __ZOLLSTOCK_TESTS_REQUIRED_FEATURES_HPP__
#define __ZOLLSTOCK_TESTS_REQUIRED_FEATURES_HPP__


#include <zollstock/tests/features.hpp>


inline const feature_set features{
    "zollstock",
    "zollstock.quantities",
    "zollstock.quantities.concepts",
    "zollstock.quantities.concepts.quantity",
    "zollstock.quantities.concepts.dimensionless",
    "zollstock.quantities.concepts.time",
    "zollstock.quantities.concepts.length",
    "zollstock.quantities.concepts.mass",
    "zollstock.quantities.concepts.electric_current",
    "zollstock.quantities.concepts.temperature",
    "zollstock.quantities.concepts.amount_of_substance",
    "zollstock.quantities.concepts.planar_angle",
    "zollstock.quantities.concepts.area",
    "zollstock.quantities.concepts.volume",
    "zollstock.quantities.constants",
    "zollstock.quantities.limits",
    "zollstock.quantities.math",
    "zollstock.quantities.quantity",
    "zollstock.units",
    "zollstock.units.concepts",
    "zollstock.units.concepts.prefix",
    "zollstock.units.concepts.unit",
    "zollstock.units.base",
    "zollstock.units.derived",
    "zollstock.units.one",
    "zollstock.units.time",
    "zollstock.units.length",
    "zollstock.units.mass",
    "zollstock.units.electric_current",
    "zollstock.units.temperature",
    "zollstock.units.amount_of_substance",
    "zollstock.units.planar_angle",
    "zollstock.units.area",
    "zollstock.units.volume",
    "zollstock.units.constants",
    "zollstock.units.constants.base",
    "zollstock.units.constants.derived",
    "zollstock.units.constants.one",
    "zollstock.units.constants.time",
    "zollstock.units.constants.length",
    "zollstock.units.constants.mass",
    "zollstock.units.constants.electric_current",
    "zollstock.units.constants.temperature",
    "zollstock.units.constants.amount_of_substance",
    "zollstock.units.constants.planar_angle",
    "zollstock.units.constants.area",
    "zollstock.units.constants.volume",
    "zollstock.units.constants.squared_time",
    "zollstock.units.literals",
    "zollstock.units.literals.base",
    "zollstock.units.literals.derived",
    "zollstock.units.literals.one",
    "zollstock.units.literals.time",
    "zollstock.units.literals.length",
    "zollstock.units.literals.mass",
    "zollstock.units.literals.electric_current",
    "zollstock.units.literals.temperature",
    "zollstock.units.literals.amount_of_substance",
    "zollstock.units.literals.planar_angle",
    "zollstock.units.literals.area",
    "zollstock.units.literals.volume"
};

inline const feature_dependencies additional_feature_deps{
    { "zollstock.units.time"               , "zollstock.units.constants.time"                },
    { "zollstock.units.time"               , "zollstock.units.literals.time"                 },
    { "zollstock.units.length"             , "zollstock.units.constants.length"              },
    { "zollstock.units.length"             , "zollstock.units.literals.length"               },
    { "zollstock.units.mass"               , "zollstock.units.constants.mass"                },
    { "zollstock.units.mass"               , "zollstock.units.literals.mass"                 },
    { "zollstock.units.temperature"        , "zollstock.units.constants.temperature"         },
    { "zollstock.units.temperature"        , "zollstock.units.literals.temperature"          },
    { "zollstock.units.amount_of_substance", "zollstock.units.constants.amount_of_substance" },
    { "zollstock.units.amount_of_substance", "zollstock.units.literals.amount_of_substance"  },
    { "zollstock.units.electric_current"   , "zollstock.units.constants.electric_current"    },
    { "zollstock.units.electric_current"   , "zollstock.units.literals.electric_current"     },
    { "zollstock.units.planar_angle"       , "zollstock.units.constants.planar_angle"        },
    { "zollstock.units.planar_angle"       , "zollstock.units.literals.planar_angle"         },
    { "zollstock.units.area"               , "zollstock.units.constants.area"                },
    { "zollstock.units.area"               , "zollstock.units.literals.area"                 },
    { "zollstock.units.volume"             , "zollstock.units.constants.volume"              },
    { "zollstock.units.volume"             , "zollstock.units.literals.volume"               },
    { "zollstock.units.constants.base"     , "zollstock.units.constants.one"                 },
    { "zollstock.units.constants.base"     , "zollstock.units.constants.time"                },
    { "zollstock.units.constants.base"     , "zollstock.units.constants.length"              },
    { "zollstock.units.constants.base"     , "zollstock.units.constants.mass"                },
    { "zollstock.units.constants.base"     , "zollstock.units.constants.temperature"         },
    { "zollstock.units.constants.base"     , "zollstock.units.constants.amount_of_substance" },
    { "zollstock.units.constants.base"     , "zollstock.units.constants.electric_current"    },
    { "zollstock.units.constants.derived"  , "zollstock.units.constants.one"                 },
    { "zollstock.units.constants.derived"  , "zollstock.units.constants.planar_angle"        },
    { "zollstock.units.constants.derived"  , "zollstock.units.constants.area"                },
    { "zollstock.units.constants.derived"  , "zollstock.units.constants.volume"              },
    { "zollstock.units.constants.derived"  , "zollstock.units.constants.squared_time"        },
    { "zollstock.units.literals.base"      , "zollstock.units.literals.one"                  },
    { "zollstock.units.literals.base"      , "zollstock.units.literals.time"                 },
    { "zollstock.units.literals.base"      , "zollstock.units.literals.length"               },
    { "zollstock.units.literals.base"      , "zollstock.units.literals.mass"                 },
    { "zollstock.units.literals.base"      , "zollstock.units.literals.temperature"          },
    { "zollstock.units.literals.base"      , "zollstock.units.literals.amount_of_substance"  },
    { "zollstock.units.literals.base"      , "zollstock.units.literals.electric_current"     },
    { "zollstock.units.literals.derived"   , "zollstock.units.literals.one"                  },
    { "zollstock.units.literals.derived"   , "zollstock.units.literals.planar_angle"         },
    { "zollstock.units.literals.derived"   , "zollstock.units.literals.area"                 },
    { "zollstock.units.literals.derived"   , "zollstock.units.literals.volume"               },
};


#endif //__ZOLLSTOCK_TESTS_REQUIRED_FEATURES_HPP__
