#ifndef __ZOLLSTOCK_CONFIG_HPP__
#define __ZOLLSTOCK_CONFIG_HPP__


#ifndef ZOLLSTOCK_MODULE_EXPORT
#  ifdef ZOLLSTOCK_USE_MODULES
#    define ZOLLSTOCK_MODULE_EXPORT export
#  else
#    define ZOLLSTOCK_MODULE_EXPORT
#  endif
#endif


#endif //__ZOLLSTOCK_CONFIG_HPP__
